### ISSUE TITLE
Weird bug disconnecting user

### ISSUE THREAD

**Issue by kaal-1** [xsun2001/Applied-Energistics-2-Unofficial#10]
Thermos server using forge 1614, and AE beta 11: When I open an ME terminal, I get a "Fatal error occurred" screen, and this error on multimc console:
https://pastebin.com/iD7syiFu

No error in server console, just player gets discconected.

Any idea of what may be causing this?

**Comment by xsun2001** [comment]
Eh...I have no idea of it. But it seems that some software changed something inside minecraft. I always play in the Thermos server and it works well. What mods or plugins or software did you use? Does this problem appear with AE beta-6(the official version)? Does this problem still exist only with AE2? I am sorry for so many questions and too late response. I hope I can help you.

**Comment by kaal-1** [comment]
I found the problem, it's the Applied Exchange mod, it works in a weird way where it tracks the name of the AE2 mod file lol... with rv6 it works just fine. It's a pretty useless mod in my opinion though, and it can be removed from the client only, so that works for me. Thank you :)
