### ISSUE TITLE
interactEvent (ME-Terminal) is being fired in the wrong place

### ISSUE THREAD

**Issue by EverNife** [xsun2001/Applied-Energistics-2-Unofficial#11]
I have a plugin (GriefPrevention) that checks if the interact-event was fired near a claim of another player, and then if it was, the event is cancelled.

Since last update all my player's get notified from my Spawn claim.

The problem is that the Spawn is centered in the coords x=0,y=0

I make a few tests and discovered that the interact event simulated that the ME-Terminal is in the coords 0,0

I am not sure if i made myself clear. So i will draw to make it easy ^^

![image](https://user-images.githubusercontent.com/11357801/29223007-5bf347fc-7e9b-11e7-81ea-82c7fe2c64ac.png)

-----
When the player right-clicks on the terminal, the interact-vent fired says that he actually clicked on the coords 0,0 and then get acces denied.

If i remove my claim, or just give permission on that single block (Coords 0,0), the player can normally acces his terminal.
Strangely the player can acces the terminal with bare hands though.

-----

Finally i tested with WorldGuard and created a region with interact deny, still getting the same results.

-----
Resuming all this... the event is fired from coords 0.0 and not from the coords of the block. :D

**Comment by xsun2001** [comment]
Thanks for your report and patience!! This bug is caused by my carelessness and I am unfamiliar with some api. I will read the javadoc first when I am going to do something. :D
