### ISSUE TITLE
craftingCalculationTimePerTick - AutoCrafting lag controller

### ISSUE THREAD

**Issue by EverNife** [xsun2001/Applied-Energistics-2-Unofficial#14]
Its common know that the craft system can cause a lot of lag on a server.

On the 1.10 version there is a config `craftingCalculationTimePerTick` (commented here https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1263)

Do you think its possible to implement on 1.7.10, or the 1.10 system of auto-crafting is too different ?

That would probably help us :D

**Comment by xsun2001** [comment]
Well...It seems that 1.7.10's AE2 **has** the `craftingCalculationTimePerTick` config.
Or you means you need me to implement the 1.10's auto-crafting system?

**Comment by EverNife** [comment]
i am a dumb... sorry '-'

Forget it
