### ISSUE TITLE
java.lang.NullPointerException: at QuantumCluster.java line 70

### ISSUE THREAD

**Issue by bartimaeusnek** [xsun2001/Applied-Energistics-2-Unofficial#18]
hey just wanted to share this with you: https://github.com/GTNewHorizons/NewHorizons/issues/2629
tried already to fix this with a null check, which didnt work tho, maybe remove final modifier? i will further try this and create a pull request if i manage to repair it.

**Comment by xsun2001** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2235
It should be a existed issue. You can have a look at the Official response. Checking `this.center` might hide the crash, which you can have a try.
