### ISSUE TITLE
crash with ars magic

### ISSUE THREAD

**Issue by EduardoMGP** [xsun2001/Applied-Energistics-2-Unofficial#19]
Hello, when adding the Unofficial applied with the magic mod ars it causes crash in the minecraft when clicking on some cable or terminal of the mod
returning this error.
is it possible to solve it? Thanks in advance

https://pastebin.com/WpxvyKkw

**Comment by LemADEC** [comment]
Is that still reproduce?

**Comment by EduardoMGP** [comment]
> Is that still reproduce?

yes it still continues

**Comment by LemADEC** [comment]
why did you close the case then?

**Comment by EduardoMGP** [comment]
I do not remember the reason I closed it back then, it's been a long time.
but I think it's because I found it a bit abandoned, few inssues have had a solution
