### ISSUE TITLE
Duplication bug :D

### ISSUE THREAD

**Issue by runescapejon** [xsun2001/Applied-Energistics-2-Unofficial#2]
Hey thanks for keep supporting 1.7.10,

anyways there this 1 duplication bug found here how to do it 

[GIF](https://cdn.discordapp.com/attachments/215217656670715904/287765770916593664/enderio.gif)

**Comment by xsun2001** [comment]
Thanks for the report. But I think it is not the issue of ae2. EnderIO's conduit may transport items unsynchronized. Please use other conduit to test. I will try to find the cause of this problem. Sorry for my poor English.

**Comment by runescapejon** [comment]
your english is good don't worry but i will test more conduit but for more information, you don't really need item buffer you can do this with a different items that can store stuff example have 2 chest, it just so happen to be item conduits because transport item but from what i understand you can do this with any pipes that can suck out from a chest and transport them to another. but will do more testing

**Comment by runescapejon** [comment]
it works Extra Utilities mod Transfer node with Transfer pipe so i highly believe it's ae2 mod

**Comment by runescapejon** [comment]
it works with any container (strongbox, chest, etc) you just need! item conduits, so i guess you right is it fixable tho ?

**Comment by xsun2001** [comment]
I will try to find the cause in AE2. But I find if you use a BC wooden pipe, it will work fine. And I think chest will not work, because the items in the chest will enter the ME Network, or I misunderstand you?

**Comment by runescapejon** [comment]
Opps my bad i meant to say Strongbox chest it's from Thermal Expansion mod and only item conduits works i had already tried wooden pipe it does not dupe

**Comment by xsun2001** [comment]
We still need to make sure that this issue is our bug or not. BC's pipe is good but EnderIO's pipe is bad. We need to find more pipes that may reproduce this issue. I don't have too much time to find them because I am studying in a **Chinese** Senior High. So trouble you to help me find them. If this bug is confirmed to be my problem, I will do my best to fix it.

**Comment by runescapejon** [comment]
okay i have tried all the pipes from different's mods and i can only reduce this problem with Enderio pipes (Item conduits)

**Comment by Eufranio** [comment]
```
BC's pipe is good but EnderIO's pipe is bad
```
AE2 is bad by not firing a block break event on the anihillation plane break (that is respected by EnderIO), both parts are wrong here. You can fix it by the AE2 side by introducing a break event.

**Comment by EverNife** [comment]
Else it would help "region protection" plugins, like Grief Prevention :D

**Comment by Eufranio** [comment]
No, it would not since there is no need to use fake players in that case.

**Comment by xsun2001** [comment]
I try to post a BlockEvent.BreakEvent when the annihilation plane breaks a block, but it seems not work. I don't know a lot about the EnderIO's conduit. I think I should to read its code...

**Comment by Eufranio** [comment]
Probably. I tested in dev and realized that the conduits will "reload" the network and repeat the checks if a break event is fired. Not firing them will make the conduit not reload and just extract. Maybe other thing in the AE2 code...

**Comment by xsun2001** [comment]
I am terrible sorry but I cannot fix this bug. Due to EnderIO doesn't use 'onNeighborChanged' to update its item conduit in its **1.7.10 version**. So I think I cannot fix this bug in AE2's controlled area. But EnderIO is discontinued to maintain too..... I am sorry for your 2-mouth waiting but to receive a bad result.

**Comment by Eufranio** [comment]
The dev said it uses, doesn't it?

**Comment by Eufranio** [comment]
@xsun2001?

**Comment by xsun2001** [comment]
@Eufranio No,they don't do that in 1.7.10.
![9k 0fl g8p7cvn y6 c9jn](https://cloud.githubusercontent.com/assets/14010993/25551383/a7e1e240-2cb6-11e7-8199-761d46f8b129.png)
left is `master` branch which is for mc1.7.10 and right is `1.10` branch.

**Comment by EverNife** [comment]
Lets recompile them too :v:

**Comment by Eufranio** [comment]
What do you think about using [Mixin](https://github.com/SpongePowered/Mixin) to add the event yourself/refresh the network when EnderIO is present? If the dev approves, ofc.

**Comment by xsun2001** [comment]
It may be a good method. If add the `onNeighborChanged` method to ItemConduit can really solve this problem, I will try it.

**Comment by Eufranio** [comment]
Hope you can, but let the EnderIO dev know you're ASMing his mod first :P
