### ISSUE TITLE
IndexOutOfBoundsException with FMP parts

### ISSUE THREAD

**Issue by Sirse** [xsun2001/Applied-Energistics-2-Unofficial#24]
That issue caused by c5bf7f6be3c471ef39a998d5c588a11411509d96 commit

https://pastebin.com/psuwdeXK

Need to cherry-pick commit https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/e67969f52f7edd3dfdbda04dc8b3f1bcca4867b1 to fix channels calculation if grid host is not present.
I was tested it, works fine.

**Comment by xsun2001** [comment]
Thanks for your contribution. 
I’m so glad that if there is anyone who still remember my fork. I will come back in about one mouth and at that time I will be totally free. Now I have to deal with my college entrance exam so your understanding is highly appreciated. Thanks again for your help.

**Comment by Sirse** [comment]
> Thanks for your contribution.
> I’m so glad that if there is anyone who still remember my fork. I will come back in about one mouth and at that time I will be totally free. Now I have to deal with my college entrance exam so your understanding is highly appreciated. Thanks again for your help.

Good luck on the exam 😉
