### ISSUE TITLE
FireBallAPI depot broken?

### ISSUE THREAD

**Issue by Ubus99** [xsun2001/Applied-Energistics-2-Unofficial#29]
Hi, I tried building AE2U 1.7.10-rv3-beta18 today, but it seems that http://dl.tsr.me/artifactory/libs-release-local is unavailable, and the build thus errors on startup.

Are there any alternative repos?

**Comment by xsun2001** [comment]
Oh... Sorry for the delay...
Another repo has down? All right... I fixed a similar issue for ChickenBones' maven repo. And you can find additional information in this comment.
https://github.com/xsun2001/Applied-Energistics-2-Unofficial/commit/eeece639b79bbdd686ca371b6c2284ea264a89c1#commitcomment-37769531

**Comment by Ubus99** [comment]
Got it working, you can find the changes in my fork, but there are more changes so i wouldn't recommend just taking that script.
