### ISSUE TITLE
Crash on updating from beta 07 to beta 09

### ISSUE THREAD

**Issue by EverNife** [xsun2001/Applied-Energistics-2-Unofficial#3]
Follows the crash 

https://hastebin.com/kewuxuzeze.rb

**Comment by EverNife** [comment]
Same problem on beta 08

https://hastebin.com/ogerebozom.vbs

**Comment by xsun2001** [comment]
Thanks for report.
I may make some change in beta 8 which can cause this crash. In fact, i know that problem but I have no better method to solve the problem in #1 . But I cannot touch my computer until my holiday comes. I will build another version without the change of beta8. And you should change the file name of ae2 to make sure ae2 will load before tt, or it will crash too.

**Comment by xsun2001** [comment]
Another question: do you use any other server?

**Comment by EverNife** [comment]
I did not understand the question.

Are you asking me if i use this mod into others server?
Or are you asking about my server-software platform ?

**Comment by xsun2001** [comment]
I'm sorry it took me so long to get back to you........

> server-software platform 

It is right. I think i can continue my job in tomorrow evening. I am sorry for I cannot solve this quickly.

**Comment by EverNife** [comment]
No problem, do it on your time ^^
It is really helpful to have an unofficial fork doing the fixes for a old version.

> **Server Platform:** `Thermos-1.7.10-1614-57.zip`
> **Applied Addons:** `thaumicenergistics`; `ExtraCells-1.7.10-2.3.14b197`

**Comment by xsun2001** [comment]
It seems that Thermos will load a method with `@SideOnly( Side.CLIENT )` in server when it load the class `PartCableSmart`, which uses a class cannot be accessed in server named `net.minecraft.client.renderer.RenderBlocks`.
I don't know if it is the issue of Thermos or mine.........

**Comment by EverNife** [comment]
Hmm, i will try to reproduce without thermos

But it is a bit hard to find a 1.7.10 server that does not use thermos, as it is the only way to use plugins.
The ones whose does not use thermos are using sponge in 1.10

Anyway, i will try to reproduce it :D

**Comment by EverNife** [comment]
I tested with only forge, with applied 07 it works well, with 09 i get this error:

https://hastebin.com/foqozuqino.vbs

So this does'nt seems to be a thermos error

**Comment by xsun2001** [comment]
Ah, I've seen this crash, but I've only seen it in my development environment. You can try this build:
[appeng.zip](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/files/861140/appeng.zip)
This version revises beta 8 changes, which may be causing it to crash.

**Comment by EverNife** [comment]
Does this one has the 
![image](https://cloud.githubusercontent.com/assets/11357801/24212917/95edf3ae-0f0f-11e7-9c7a-8cacae5bc958.png)

?

**Comment by EverNife** [comment]
And yes, it worked well with this build you gave me

**Comment by xsun2001** [comment]
That's good. I removed the change of beta 8 in the build I gave you. I may find the problem of this crash. Hope I can fix it soon.

**Comment by xsun2001** [comment]
@evernife I think I have fixed this issue. You can test it to know. I will release a new version when I fix the only issue which is still open. I should have a CI server......
[appeng.zip](https://github.com/xsun2001/Applied-Energistics-2-Unofficial/files/864782/appeng.zip)
