### ISSUE TITLE
the oredictionary filter works mistakenly

### ISSUE THREAD

**Issue by RUEEE** [xsun2001/Applied-Energistics-2-Unofficial#31]
if  more than one symbol ( & , | ) is written in one oredictionary filter and the first conjunction is "|", the filter will process all symbols as "|".
e.g. use string "ore*|dustImpure*|dustPure*&!crushedPurifiedGalena&!crushedPurifiedGalena" for the oredictionary upgrade in ME export bus will cause all items export wrongly...

**in util/prioitylist/oreFilteredList , line 82**
the varible "lastFilter" will never update after inited as the first filter, which results in all the symbols except the first one and other "|" is ignored

**Comment by EverNife** [comment]
Last update on this repo is from  7 Dec 2019

I would suggest you to try this bug on the most recent Unofficial Applied we have, the one from https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial

If the bug perssist, open an issue there :D
