### ISSUE TITLE
Add events in Formation/Anihillation planes

### ISSUE THREAD

**Issue by Eufranio** [xsun2001/Applied-Energistics-2-Unofficial#4]
They currently bypass anything that listens to the break/place event.

**Comment by xsun2001** [comment]
I think that enderio update their pipe network every server tick, no by listening the break event.Formation/Anihillation planes do their work too fast to let enderio update network. I will do more test on my env. If firing those events can get more adventages, such as peotect the personal area, I will add it. But recently when I try to reproduce that dupe bug, it disappare. For detail, the Formation planes will not place the block any more. I dont know weather it is a another bug that I made or I set up the network incorrectly. I will do more work on it when I am free.
I am sorry for ignoring the issue2 for a mouth and I am sorry for my English again.

>  I have pressed the wrong button.....

**Comment by Eufranio** [comment]
I'm not talking about EnderIO, I'm talking about any modern well-coded mod (that listens for events).

**Comment by xsun2001** [comment]
eh......You.may be right. So should we just add the code for events, or use FakePlayer instead?

**Comment by Eufranio** [comment]
If you can, fake players ofc. Just caution with the amount of checks, since Formation/Anihillation planes works quickly, a high spam of permission checks would overhead the server/permission system. I suggest implement a cache for the fake player checks.

**Comment by xsun2001** [comment]
Do you mean we should use cache for the blocks to check if it can be broken? Or the cache for FakePlayer?

**Comment by Eufranio** [comment]
Cache for the fake player permission checks, like a interval between each check. Let's say we have 30 Formation Planes loaded: they will be each tick (or 2, I'm unsure) trying to place a block, and AE2 would be requesting the permission check. The permission plugin would have to proccess EACH check, EACH tick, it could overhead.

I suggest you checking maybe 1 time per 20 ticks? If the first check is valid and true (if so the fake player can place the blocks), cache that check and always return true for the other 19 ticks. Once completed, make a new check, and etc.

**Comment by xsun2001** [comment]
I think I have done this job. You can get the newest build from [appveyor](https://ci.appveyor.com/project/xsun2001/applied-energistics-2-unofficial/build/rv3-1.7.10-build5/artifacts) and check if you can stop the planes by cancelling its events. The fake player's name is '[AE2Player]'. I only added the cache for Annihilation Plane because another plane is not tickable, and it usually not be used very quickly. @Eufranio Thanks for report!

EDIT:If you find some problem with the events, such as it cannot prevent the planes working, you can open a new issue.
