### ISSUE TITLE
Add a Interact on wrench/right click

### ISSUE THREAD

**Issue by Eufranio** [xsun2001/Applied-Energistics-2-Unofficial#6]
ATM AE2 just sends some packets from the client to the server know that it clicked something, so there is no way to listen for those packets. I suggest you adding a interact when a player uses a wrench in a AE2 block (and check if it's not cancelled), and also when right clicking AE2 blocks (such as terminals).

**Comment by xsun2001** [comment]
I do not really understand what is the meaning of "interact" because of my poor English, althrough there is some online translater. Did you mean we should send packets that contains the information of what I clicked or something else?

**Comment by Eufranio** [comment]
Interact is the event fired when someone right/left click something, collide with a pressure plate, jump, walk over specific blocks, etc. They are called "interactions", see: http://www.minecraftforge.net/forum/topic/25346-right-click-event-that-triggers-after-block-interaction/

My suggestion is that when someone **right click** anything from a network, BEFORE the original logic be made, include a PlayerInteractEvent. This event can be cancelled by the bukkit or forge side, meaning that bukkit plugins and forge mods can track the right clicked blocks.

As this page says, you can **add a PlayerInteractEvent** every time a AE2 blocks is clicked. Then, check if it is cancelled (`event.isCancelled()`), and if it is **not** cancelled, run the rest of the logic (such as permission checks by the security station, etc).

**Comment by xsun2001** [comment]
I have added 'PlayerInteractEvent' for ME network parts and 'PlayerUseItemEvent.Start' for some items which will do something special when right click. @Eufranio If you think it is good enough, you can close it youself, or you can ask me for the further improve.

**Comment by Eufranio** [comment]
That's good, thanks!
