### ISSUE TITLE
Another Massive Dupe :V

### ISSUE THREAD

**Issue by EverNife** [xsun2001/Applied-Energistics-2-Unofficial#9]
One of my player's reported a dupe bug....

Step by step:
1- Open the MePatternTerminal
2- Put any item you want to dupe, for exemple, diamonds...

![image](https://cloud.githubusercontent.com/assets/11357801/26750223/a9f8bce0-47f3-11e7-9a90-e9a55a8d6473.png)

3- Hold SHIFT + SPACE_BAR and click the "White-Arrow"

![image](https://cloud.githubusercontent.com/assets/11357801/26750227/c1040f16-47f3-11e7-8482-90aa58a6da82.png)

4- Still holding SHIFT + SPACE_BAR click on the item to dupe.

![image](https://cloud.githubusercontent.com/assets/11357801/26750234/d038f0a0-47f3-11e7-8419-a46d373f6df1.png)

Repeat the procces how many time do you want.
As simple as that :v: 

+ A video here to show how it works better :V
https://www.youtube.com/watch?v=6Hr-MJHexu4&feature=youtu.be

**Comment by xsun2001** [comment]
I have fixed the bug in the commit and you can get the version which has the fix from the [AppVeyor ](https://ci.appveyor.com/api/buildjobs/60uceqtg0sloy07k/artifacts/build%2Flibs%2Fappliedenergistics2-rv3-beta-11.jar)CI server. But I don't know if what I did will cause some other problem. If this fix works, you can close this issue by yourself.

**Comment by EverNife** [comment]
Pretty well fixed :V

**Comment by vaIgarashi** [comment]
It's fixed only for the client-side. If i download non-patched AE i still could dupe.

**Comment by EverNife** [comment]
so we need just to force the person to use the same version of the server :D

**Comment by xsun2001** [comment]
@ensirius It's fixed only for the client because the issue is **only** a client bug. It caused by a consider inadequate operation in client's key board event handling. So as @evernife said, the solution is force player to use the latest version or use the anti-cheat mod to prevent the player with incompatible mods to log in the server.

**Comment by vaIgarashi** [comment]
@xsun2001 You are **wrong**. Server side just don't handle logic properly.

**Comment by xsun2001** [comment]
@ensirius e... Now I think you needn't to worry about the player with the older version AE2.
